name: .NET API CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.sln'
      - 'appsettings.json'
  pull_request:
    branches: [main]
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.sln'
      - 'appsettings.json'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
      
    - name: Publish
      run: dotnet publish --configuration Release --output $GITHUB_WORKSPACE/publish
      
    - name: List publish directory contents
      run: ls -la $GITHUB_WORKSPACE/publish
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: api-build
        path: $GITHUB_WORKSPACE/publish

  deploy:
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: api-build
        path: $GITHUB_WORKSPACE/publish
        
    - name: List downloaded contents
      run: ls -la $GITHUB_WORKSPACE/publish
      
    # Deployment to Azure App Service
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'reem-rpg-api'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: $GITHUB_WORKSPACE/publish