name: Deploy to Azure

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.1' 

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Publish project
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to Azure
        env:
          SMTP_USERNAME: ${{ secrets.SMTPUSERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTPPASSWORD }}
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE.reem-rpg-api}}
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
          package: ./publish
